

```{r}
library(openxlsx)
library(stringr)
library(knitr)
```


```{r, wb=TRUE}
# wb <- createWorkbook()
# addWorksheet(wb, "Sheet 1")

text <- c("* fruits
  + apples
    - macintosh
    - red delicious
  + pears
  + peaches", "* vegetables
  + broccoli
  + chard")

text <- str_split(text, "\n")
text <- purrr::flatten_chr(text)


writeData(wb, 1, text)
style <- createStyle(fontColour = "red", textDecoration = "bold")
addStyle(wb, 1, style, 1, 1)

# openXL(wb)
```


# Vectors

## Vertical without names

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

x <- 1:4
writeData(wb, 1, x, 1, 1)

openXL(wb)
```

## Vertical with names

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

x <- 1:4
names(x) <- letters[1:4]
x <- as.data.frame(x)
writeData(wb, 1, x, 1, 1, rowNames = TRUE, colNames = FALSE)

openXL(wb)
```

## Horizontal without names

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

x <- 1:4
x <- t(x)
writeData(wb, 1, x, 1, 1, colNames = FALSE)

openXL(wb)
```

## Horizontal with names

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

x <- 1:4
names(x) <- letters[1:4]
x <- t(x)
writeData(wb, 1, x, 1, 1)

openXL(wb)
```

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

writeData(wb, 1, mtcars, 1, 1, rowNames = TRUE)

openXL(wb)
```


## Heights

```{r}
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")

setRowHeights(wb, 1, 2, 15)

openXL(wb)
```

## Figures

```{r}
png()
```

